name: Validate and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Csak a main branch-re történő push esetén fut le

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Repository klónozása
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Node.js telepítése
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Vagy a projektedhez szükséges verzió

    # 3. Függőségek telepítése
    - name: Install dependencies
      run: npm install

    # 4. JSON validáció futtatása
    - name: Run validation
      run: node validate.js

    # 5. Deploy GitHub Pages-re (ha a validáció sikeres volt)
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ # A deploy-olandó fájlok könyvtára